apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata:
  name: noah-birdboard-ml-tls
spec:
  secretName: noah-birdboard-ml
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: noah-birdboard.ml
  dnsNames:
    - noah-birdboard.ml
    - www.noah-birdboard.ml
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - noah-birdboard.ml
          - www.noah-birdboard.ml
